services:
  db:
    image: postgres:16 # (Notice this is still showing as 18 in your terminal, make sure to change it!)
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: jokespot
    ports:
      - "5432:5432"    # <-- THIS IS THE MISSING PIECE!
    volumes:
      - ./src/init_data:/docker-entrypoint-initdb.d