INSERT INTO users
    (username, password)
VALUES
    ('user0', '$2a$10$E.Nq8oyJqsqC45g.38Rkj.Wvgya2p1PBH/LM4F1scBxXgbTrRlASG');

INSERT INTO jokes 
    (author, content, tags)
VALUES
    ('user0', 'Why don''t scientists trust atoms? Because they make up everything.', 'science,puns'),
    ('user0', 'I told my wife she was drawing her eyebrows too high. She looked surprised.', 'puns,relationships'),
    ('user0', 'What do you call a fake noodle? An impasta.', 'food,puns'),
    ('user0', 'Why did the scarecrow win an award? Because he was outstanding in his field.', 'wordplay,puns'),
    ('user0', 'I''m reading a book about anti-gravity. It''s impossible to put down.', 'books,puns'),
    ('user0', 'Did you hear about the mathematician who''s afraid of negative numbers? He''ll stop at nothing to avoid them.', 'math,puns'),
    ('user0', 'Why can''t you give Elsa a balloon? Because she''ll let it go.', 'movies,puns'),
    ('user0', 'I used to hate facial hair, but then it grew on me.', 'puns,wordplay'),
    ('user0', 'What do you call cheese that isn''t yours? Nacho cheese.', 'food,puns'),
    ('user0', 'Why did the bicycle fall over? Because it was two-tired.', 'puns,wordplay'),
    ('user0', 'I''m on a seafood diet. I see food and I eat it.', 'food,wordplay'),
    ('user0', 'What do you call a sleeping dinosaur? A dino-snore.', 'animals,puns'),
    ('user0', 'Why do cows wear bells? Because their horns don''t work.', 'animals,puns'),
    ('user0', 'What did the ocean say to the beach? Nothing, it just waved.', 'nature,puns'),
    ('user0', 'Why don''t eggs tell jokes? They''d crack each other up.', 'food,puns'),
    ('user0', 'What do you call a bear with no teeth? A gummy bear.', 'animals,food,puns'),
    ('user0', 'I told my doctor that I broke my arm in two places. He told me to stop going to those places.', 'medical,wordplay'),
    ('user0', 'What''s brown and sticky? A stick.', 'puns,wordplay'),
    ('user0', 'Why did the golfer bring an extra pair of pants? In case he got a hole in one.', 'sports,puns'),
    ('user0', 'What do you call a fish without eyes? A fsh.', 'animals,wordplay'),
    ('user0', 'Why did the math book look so sad? Because it had too many problems.', 'school,puns'),
    ('user0', 'What do you call a snowman with a six-pack? An abdominal snowman.', 'winter,puns,wordplay'),
    ('user0', 'Why don''t scientists trust atoms? Because they make up everything!', 'science,puns'),
    ('user0', 'Time flies like an arrow. Fruit flies like a banana.', 'wordplay,puns'),
    ('user0', 'What do you get when you cross a snowman and a vampire? Frostbite.', 'halloween,winter,puns'),
    ('user0', 'I wanted to learn to juggle but I didn''t have the balls to do it.', 'wordplay,puns'),
    ('user0', 'Why do programmers prefer dark mode? Because light attracts bugs.', 'tech,puns'),
    ('user0', 'A skeleton walks into a bar and orders a beer and a mop.', 'halloween,food,wordplay'),
    ('user0', 'What do you call a lazy kangaroo? A pouch potato.', 'animals,puns'),
    ('user0', 'Why did the stadium get hot after the game? All the fans left.', 'sports,puns'),
    ('user0', 'I asked my dog what two minus two is. He said nothing.', 'animals,math,wordplay'),
    ('user0', 'What did the Buddhist say to the hot dog vendor? Make me one with everything.', 'food,wordplay'),
    ('user0', 'I used to be a banker but I lost interest.', 'puns,wordplay'),
    ('user0', 'How do you organize a space party? You planet.', 'science,puns'),
    ('user0', 'What do you call a pig that does karate? A pork chop.', 'animals,food,puns'),
    ('user0', 'I''m great at sleeping. I can do it with my eyes closed.', 'wordplay,puns'),
    ('user0', 'Why did the coffee file a police report? It got mugged.', 'food,puns'),
    ('user0', 'What do you call a man with a rubber toe? Roberto.', 'puns,wordplay'),
    ('user0', 'Why can''t a nose be 12 inches long? Because then it would be a foot.', 'puns,wordplay'),
    ('user0', 'I have a joke about construction, but I''m still working on it.', 'meta,puns'),
    ('user0', 'Why don''t some couples go to the gym? Because some relationships don''t work out.', 'relationships,puns'),
    ('user0', 'What do you call an alligator in a vest? An investigator.', 'animals,puns,wordplay'),
    ('user0', 'I''m reading a horror story in Braille. Something bad is about to happen, I can feel it.', 'books,wordplay'),
    ('user0', 'Did you hear about the claustrophobic astronaut? He just needed a little space.', 'science,puns'),
    ('user0', 'Why don''t scientists trust atoms? Because they''re always making things up.', 'science,puns'),
    ('user0', 'What do you call a fake stone in Ireland? A sham rock.', 'puns,wordplay'),
    ('user0', 'I got a job at a bakery because I kneaded dough.', 'food,puns'),
    ('user0', 'Why did the invisible man turn down the job offer? He couldn''t see himself doing it.', 'wordplay,puns'),
    ('user0', 'What do Alexander the Great and Winnie the Pooh have in common? Same middle name.', 'history,wordplay'),
    ('user0', 'A man walks into a library and asks for books about paranoia. The librarian whispers, "They''re right behind you."', 'books,wordplay');